`use client`;
import "./globals.css";
import { Poppins } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "@/components/custom/header/Header";
import Sidebar from "@/components/custom/sidebar/sidebar";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} bg-background`}>
        <Providers>
          <Navbar />
          <main>
            <Sidebar />
            <section>{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
